Models/ErrorViewModel.cs
namespace CSIMedia.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/JsonSort.cs
namespace CSIMedia.Models
{
    public class JsonSort
    {
        public int Id { get; set; }


        public int[] numbers { get; set; }


        public double timeTaken { get; set; }


        public string order { get; set; }


        public DateTime CreatedDateTime { get; set; } = DateTime.Now;
    }
}

Models/NumberSequence.cs
using System.ComponentModel.DataAnnotations;

namespace CSIMedia.Models
{
    public class NumberSequence
    {
        public string numbers { get; set; }

        public string order { get; set; }

    }
}

Models/Sort.cs
using System.ComponentModel.DataAnnotations;

namespace CSIMedia.Models
{
    public class Sort
    {
        [Key]
        [Required]
        public int Id { get; set; }
        [Required]

        public string numbers { get; set; }
        [Required]

        public double timeTaken { get; set; }
        [Required]

        public string order { get; set; }
        [Required]

        public DateTime CreatedDateTime { get; set; } = DateTime.Now;
    }
}

Controllers/HomeController.cs
using CSIMedia.Data;
using CSIMedia.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Diagnostics;

namespace CSIMedia.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _database;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext database)
        {
            _logger = logger;
            _database = database;

        }

        public IActionResult Index()
        {
            var sorts = _database.Sorts;
            return View(sorts);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public async Task<IActionResult> Delete(int? id)
        {
            var sort = _database.Sorts.Find(id);
            _database.Sorts.Remove(sort);
            await _database.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public IActionResult JSON()
        {
            // Download database as JSON. TODO
            var sorts = _database.Sorts.ToList();
            // Convert to JSON format
            var jsonSorts = createJsonSorts(sorts);
            var jsonContent = JsonConvert.SerializeObject(jsonSorts, Formatting.Indented);
            var jsonBytes = System.Text.Encoding.UTF8.GetBytes(jsonContent);
            return File(jsonBytes, "application/json", "Sorts.json");
        }

        private List<JsonSort> createJsonSorts(List<Sort> sorts)
        {
            // linq 
            var jsonSorts = sorts.Select(sort => new JsonSort
            {
                Id = sort.Id,
                numbers = sort.numbers.Split(',').Select(numberString =>
                {
                    if (int.TryParse(numberString, out int number))
                    {
                        return number;
                    } else
                    {
                        //defualt case can be 0 but this shouldnt happen because it was validated before entering database
                        return 0;
                    }
                }).ToArray(),
                timeTaken = sort.timeTaken,
                order = sort.order,
                CreatedDateTime = sort.CreatedDateTime
            }).ToList();

            return jsonSorts;
        }

        
    }
}

Controllers/SortController.cs
using CSIMedia.Data;
using CSIMedia.Models;
using CSIMedia.Sorting;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CSIMedia.Controllers
{
    public class SortController : Controller
    {
        private readonly ApplicationDbContext _database;
        private readonly ISortingService _sortingService;

        public SortController(ApplicationDbContext database, ISortingService sortingService)
        {
            _database = database;
            _sortingService = sortingService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(Sort sequence)
        {
            if(ModelState.IsValid)
            {
                // Main logic 
                /*
                 * 1. Validate the sequence of numbers is comma separated and create an array
                 * 2. Get sorting order
                 * 3. Sort numbers
                 * 4. Create a Sort object and store in database
                 */

                var sequenceStrings = sequence.numbers.Split(',');
                var integers = new int[sequenceStrings.Length];

                // Try to parse each number into an int type
                for (int i = 0; i < sequenceStrings.Length; i++)
                {
                    if (int.TryParse(sequenceStrings[i], out int num))
                    {
                        integers[i] = num;
                    } else
                    {
                        ModelState.AddModelError("CustomError", "Invalid number sequence format");
                        return View(sequence);
                    }
                }

                // Get the sorting order
                var sortingOrder = sequence.order.ToString();
                // Start the timer
                Stopwatch sw = Stopwatch.StartNew();

                if(sortingOrder == "Ascending")
                {
                    // Sort into ascending order
                    integers = _sortingService.sortAsc(integers);
                }
                else
                {
                    // Sort into descending order
                    integers = _sortingService.sortDesc(integers);
                }
                // Stop the timer
                var ms = sw.Elapsed.TotalMilliseconds;
                sw.Stop();

                // Update the Sort object
                sequence.numbers = string.Join(",", integers);
                sequence.timeTaken = ms;

                // Add to the database
                await _database.Sorts.AddAsync(sequence);
                await _database.SaveChangesAsync();

                TempData["success"] = "Sequence created successfully";

                return RedirectToAction("Index", "Home");
            }
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model IEnumerable<Sort>

<div class="container">
    <div class="row pt-4">
        <div class="col-6">
            <h1 class="text-primary">Number Sorter</h1>
            @if (TempData["success"] != null)
            {
                <h4 class="text-success">@TempData["success"]</h4>
            }
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Sort" asp-action="Index" class="btn btn-primary">
                Create sequence
            </a>
        </div>
    </div>
</div>



<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Sequence
            </th>
            <th>
                Time Taken (ms)
            </th>
            <th>
                Order
            </th>
            <th>
                <a asp-asp-controller="Home" asp-action="JSON" class="btn btn-warning mx-2">
                    JSON <i class="bi bi-file-earmark-arrow-down-fill"></i>
                </a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            <tr>
                <td width="50%">
                    @obj.numbers
                </td>
                <td width="20%">
                    @obj.timeTaken
                </td>
                <td width="20%">
                    @obj.order
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Home" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2">
                            Delete
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CSIMedia</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CSIMedia.styles.css" asp-append-version="true" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CSIMedia</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sort" asp-action="Index">Create sequence</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CSIMedia - Lewis Heath Coding Challenge
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Sort/Index.cshtml
@model Sort

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Sequence</h2>
            <hr />
        </div>
        <p>Please enter numbers separated by commas (,)</p>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="numbers">Numbers</label>
            <input asp-for="numbers" class="form-control" name="numbers" id="numbers" />
            <span asp-validation-for="numbers" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="order">Sort Order</label>
            @*<input asp-for="order" class="form-control" name="order" id="order"/>*@
            <select asp-for="order">
                <option>Ascending</option>
                <option>Descending</option>
            </select>
            <span asp-validation-for="order" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="Home" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to Home</a>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}